# Generated by Django 4.1.3 on 2023-11-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('image', models.TextField(max_length=500)),
                ('price', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='mkd',
        ),
    ]
